//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyEnergy.Gym.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDTO", Namespace="http://schemas.datacontract.org/2004/07/Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Data.DTO.AsistenciaDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Data.DTO.EmpresaDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Data.DTO.ContactoEmpresaDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Data.DTO.TipoSocioDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Data.DTO.SocioDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Data.DTO.FechaVencimientoDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Data.DTO.TransaccionDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Data.DTO.TipoPagoDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Data.DTO.CategoriaPagoDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Data.DTO.SeguridadDTO))]
    public partial class BaseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsDirtyk__BackingFieldField;
        
        private BodyEnergy.Gym.Service.ObjectMethod Methodk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsDirty>k__BackingField", IsRequired=true)]
        public bool IsDirtyk__BackingField {
            get {
                return this.IsDirtyk__BackingFieldField;
            }
            set {
                if ((this.IsDirtyk__BackingFieldField.Equals(value) != true)) {
                    this.IsDirtyk__BackingFieldField = value;
                    this.RaisePropertyChanged("IsDirtyk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Method>k__BackingField", IsRequired=true)]
        public BodyEnergy.Gym.Service.ObjectMethod Methodk__BackingField {
            get {
                return this.Methodk__BackingFieldField;
            }
            set {
                if ((this.Methodk__BackingFieldField.Equals(value) != true)) {
                    this.Methodk__BackingFieldField = value;
                    this.RaisePropertyChanged("Methodk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectMethod", Namespace="http://schemas.datacontract.org/2004/07/Common")]
    public enum ObjectMethod : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modify = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Gym.Service.ISoapService")]
    public interface ISoapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerUsuario", ReplyAction="http://tempuri.org/ISoapService/ObtenerUsuarioResponse")]
        Data.DTO.SeguridadDTO ObtenerUsuario(string pUsuario, string pContrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerAsistenciasBusqueda", ReplyAction="http://tempuri.org/ISoapService/ObtenerAsistenciasBusquedaResponse")]
        string ObtenerAsistenciasBusqueda(int pCodSocio, string pFechaI, string pFechaF, bool pHoy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/BorrarAsistencia", ReplyAction="http://tempuri.org/ISoapService/BorrarAsistenciaResponse")]
        void BorrarAsistencia(int pCodAsistencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/SaveAttendance", ReplyAction="http://tempuri.org/ISoapService/SaveAttendanceResponse")]
        void SaveAttendance(Data.DTO.AsistenciaDTO asistDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerContactoEmpresasBusqueda", ReplyAction="http://tempuri.org/ISoapService/ObtenerContactoEmpresasBusquedaResponse")]
        string ObtenerContactoEmpresasBusqueda(string pNombreCompleto, int pCodEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerTodosEmpresa", ReplyAction="http://tempuri.org/ISoapService/ObtenerTodosEmpresaResponse")]
        System.Collections.Generic.List<Data.DTO.EmpresaDTO> ObtenerTodosEmpresa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerEmpresasBusqueda", ReplyAction="http://tempuri.org/ISoapService/ObtenerEmpresasBusquedaResponse")]
        string ObtenerEmpresasBusqueda(string pNombreEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerContacto", ReplyAction="http://tempuri.org/ISoapService/ObtenerContactoResponse")]
        Data.DTO.ContactoEmpresaDTO ObtenerContacto(int pCodContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/SaveContact", ReplyAction="http://tempuri.org/ISoapService/SaveContactResponse")]
        void SaveContact(Data.DTO.ContactoEmpresaDTO cxeDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/SaveEnterprise", ReplyAction="http://tempuri.org/ISoapService/SaveEnterpriseResponse")]
        void SaveEnterprise(Data.DTO.EmpresaDTO empDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerEmpresa", ReplyAction="http://tempuri.org/ISoapService/ObtenerEmpresaResponse")]
        Data.DTO.EmpresaDTO ObtenerEmpresa(int pCodEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerTipoSocio", ReplyAction="http://tempuri.org/ISoapService/ObtenerTipoSocioResponse")]
        Data.DTO.TipoSocioDTO ObtenerTipoSocio(int pCodTipoSocio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerTodosTipoSocio", ReplyAction="http://tempuri.org/ISoapService/ObtenerTodosTipoSocioResponse")]
        System.Collections.Generic.List<Data.DTO.TipoSocioDTO> ObtenerTodosTipoSocio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerSociosBusqueda", ReplyAction="http://tempuri.org/ISoapService/ObtenerSociosBusquedaResponse")]
        string ObtenerSociosBusqueda(string pNombreCompleto, int pCodTipoSocio, int pCodEmpresa, string pFecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerSocio", ReplyAction="http://tempuri.org/ISoapService/ObtenerSocioResponse")]
        Data.DTO.SocioDTO ObtenerSocio(int pCodSocio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerFecha", ReplyAction="http://tempuri.org/ISoapService/ObtenerFechaResponse")]
        Data.DTO.FechaVencimientoDTO ObtenerFecha(int pCodSocio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerFecVencimiento", ReplyAction="http://tempuri.org/ISoapService/ObtenerFecVencimientoResponse")]
        Data.DTO.FechaVencimientoDTO ObtenerFecVencimiento(int pCodSocio, int pCodCortesia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/SaveExpireDate", ReplyAction="http://tempuri.org/ISoapService/SaveExpireDateResponse")]
        void SaveExpireDate(Data.DTO.FechaVencimientoDTO fecDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/SaveSocio", ReplyAction="http://tempuri.org/ISoapService/SaveSocioResponse")]
        int SaveSocio(Data.DTO.SocioDTO socDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerTransaccionesBusqueda", ReplyAction="http://tempuri.org/ISoapService/ObtenerTransaccionesBusquedaResponse")]
        string ObtenerTransaccionesBusqueda(int pCodSocio, int pCodTipoPago, string pFechaI, string pFechaF, string pHoy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/BorrarTransaccion", ReplyAction="http://tempuri.org/ISoapService/BorrarTransaccionResponse")]
        void BorrarTransaccion(int pCodTransaccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerMontoSocio", ReplyAction="http://tempuri.org/ISoapService/ObtenerMontoSocioResponse")]
        string ObtenerMontoSocio(int pCodSocio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerTransaccion", ReplyAction="http://tempuri.org/ISoapService/ObtenerTransaccionResponse")]
        Data.DTO.TransaccionDTO ObtenerTransaccion(int pCodTransaccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/SaveTransaction", ReplyAction="http://tempuri.org/ISoapService/SaveTransactionResponse")]
        int SaveTransaction(Data.DTO.TransaccionDTO tranDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerTodosTiposPago", ReplyAction="http://tempuri.org/ISoapService/ObtenerTodosTiposPagoResponse")]
        System.Collections.Generic.List<Data.DTO.TipoPagoDTO> ObtenerTodosTiposPago();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/ObtenerTodasCatPago", ReplyAction="http://tempuri.org/ISoapService/ObtenerTodasCatPagoResponse")]
        System.Collections.Generic.List<Data.DTO.CategoriaPagoDTO> ObtenerTodasCatPago();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISoapServiceChannel : BodyEnergy.Gym.Service.ISoapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoapServiceClient : System.ServiceModel.ClientBase<BodyEnergy.Gym.Service.ISoapService>, BodyEnergy.Gym.Service.ISoapService {
        
        public SoapServiceClient() {
        }
        
        public SoapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Data.DTO.SeguridadDTO ObtenerUsuario(string pUsuario, string pContrasenia) {
            return base.Channel.ObtenerUsuario(pUsuario, pContrasenia);
        }
        
        public string ObtenerAsistenciasBusqueda(int pCodSocio, string pFechaI, string pFechaF, bool pHoy) {
            return base.Channel.ObtenerAsistenciasBusqueda(pCodSocio, pFechaI, pFechaF, pHoy);
        }
        
        public void BorrarAsistencia(int pCodAsistencia) {
            base.Channel.BorrarAsistencia(pCodAsistencia);
        }
        
        public void SaveAttendance(Data.DTO.AsistenciaDTO asistDto) {
            base.Channel.SaveAttendance(asistDto);
        }
        
        public string ObtenerContactoEmpresasBusqueda(string pNombreCompleto, int pCodEmpresa) {
            return base.Channel.ObtenerContactoEmpresasBusqueda(pNombreCompleto, pCodEmpresa);
        }
        
        public System.Collections.Generic.List<Data.DTO.EmpresaDTO> ObtenerTodosEmpresa() {
            return base.Channel.ObtenerTodosEmpresa();
        }
        
        public string ObtenerEmpresasBusqueda(string pNombreEmpresa) {
            return base.Channel.ObtenerEmpresasBusqueda(pNombreEmpresa);
        }
        
        public Data.DTO.ContactoEmpresaDTO ObtenerContacto(int pCodContacto) {
            return base.Channel.ObtenerContacto(pCodContacto);
        }
        
        public void SaveContact(Data.DTO.ContactoEmpresaDTO cxeDto) {
            base.Channel.SaveContact(cxeDto);
        }
        
        public void SaveEnterprise(Data.DTO.EmpresaDTO empDto) {
            base.Channel.SaveEnterprise(empDto);
        }
        
        public Data.DTO.EmpresaDTO ObtenerEmpresa(int pCodEmpresa) {
            return base.Channel.ObtenerEmpresa(pCodEmpresa);
        }
        
        public Data.DTO.TipoSocioDTO ObtenerTipoSocio(int pCodTipoSocio) {
            return base.Channel.ObtenerTipoSocio(pCodTipoSocio);
        }
        
        public System.Collections.Generic.List<Data.DTO.TipoSocioDTO> ObtenerTodosTipoSocio() {
            return base.Channel.ObtenerTodosTipoSocio();
        }
        
        public string ObtenerSociosBusqueda(string pNombreCompleto, int pCodTipoSocio, int pCodEmpresa, string pFecha) {
            return base.Channel.ObtenerSociosBusqueda(pNombreCompleto, pCodTipoSocio, pCodEmpresa, pFecha);
        }
        
        public Data.DTO.SocioDTO ObtenerSocio(int pCodSocio) {
            return base.Channel.ObtenerSocio(pCodSocio);
        }
        
        public Data.DTO.FechaVencimientoDTO ObtenerFecha(int pCodSocio) {
            return base.Channel.ObtenerFecha(pCodSocio);
        }
        
        public Data.DTO.FechaVencimientoDTO ObtenerFecVencimiento(int pCodSocio, int pCodCortesia) {
            return base.Channel.ObtenerFecVencimiento(pCodSocio, pCodCortesia);
        }
        
        public void SaveExpireDate(Data.DTO.FechaVencimientoDTO fecDto) {
            base.Channel.SaveExpireDate(fecDto);
        }
        
        public int SaveSocio(Data.DTO.SocioDTO socDto) {
            return base.Channel.SaveSocio(socDto);
        }
        
        public string ObtenerTransaccionesBusqueda(int pCodSocio, int pCodTipoPago, string pFechaI, string pFechaF, string pHoy) {
            return base.Channel.ObtenerTransaccionesBusqueda(pCodSocio, pCodTipoPago, pFechaI, pFechaF, pHoy);
        }
        
        public void BorrarTransaccion(int pCodTransaccion) {
            base.Channel.BorrarTransaccion(pCodTransaccion);
        }
        
        public string ObtenerMontoSocio(int pCodSocio) {
            return base.Channel.ObtenerMontoSocio(pCodSocio);
        }
        
        public Data.DTO.TransaccionDTO ObtenerTransaccion(int pCodTransaccion) {
            return base.Channel.ObtenerTransaccion(pCodTransaccion);
        }
        
        public int SaveTransaction(Data.DTO.TransaccionDTO tranDto) {
            return base.Channel.SaveTransaction(tranDto);
        }
        
        public System.Collections.Generic.List<Data.DTO.TipoPagoDTO> ObtenerTodosTiposPago() {
            return base.Channel.ObtenerTodosTiposPago();
        }
        
        public System.Collections.Generic.List<Data.DTO.CategoriaPagoDTO> ObtenerTodasCatPago() {
            return base.Channel.ObtenerTodasCatPago();
        }
    }
}
